### ISSUE TITLE
Upgrade build_config to 1.0.0

### ISSUE THREAD

**Issue by smkhalsa** [google/built_value.dart#1025]
`build_config` now has a null-safe version (1.0.0) which is used by `build_runner` 2.0.0.

Can we upgrade `built_value` to use `build_config` ^1.0.0 so that it can be compatible with `build_runner` 2.0.0?

Thanks!

**Comment by davidmorgan** [comment]
Thanks! I think I can get to this next week.

**Comment by ab36245** [comment]
Great! This is biting me too, so allowing us to move to the latest build_runner will be a positive step.

**Comment by aarajput** [comment]
Any update about this?

**Comment by allanclempe** [comment]
+1

**Comment by Fraa-124** [comment]
We're stuck on this so can't migrate to null safety

`Because build_runner >=2.0.0 depends on build_config >=1.0.0 <1.1.0 and built_value_generator 8.0.5 depends on build_config >=0.3.1 <0.5.0, build_runner >=2.0.0 is incompatible with built_value_generator 8.0.5.`

**Comment by allanclempe** [comment]
@Fraa-124 this combination works for me. Not ideal overriding, but is a way to work around until this gets done.

```
dependencies:
  built_value: ^8.0.5
  built_collection: ^5.0.0

dev_dependencies:
  build_runner: ^2.0.1
  built_value_generator: ^8.0.5

  
dependency_overrides:
  build_config: 1.0.0

```
