### ISSUE TITLE
Type cast error for optional type

### ISSUE THREAD

**Issue by baloi91** [google/built_value.dart#1091]
Hi guys,
I ran into this issue: **type '_$TaskList' is not a subtype of type 'TaskList?' in type cast** while other classes work fine.
Am I missing something?

<img width="816" alt="type cast error" src="https://user-images.githubusercontent.com/4568462/131610598-423c1718-fa1e-4a25-8487-be962e20503f.png">

TaskList class

```
abstract class TaskList implements Built<TaskList, TaskListBuilder> {
  BuiltList<Task> get content;
  Pageable get pageable;
  int get totalPages;
  int get totalElements;
  bool get last;
  bool get first;
  Sort get sort;
  int get size;
  int get number;
  int get numberOfElements;
  bool get empty;

  TaskList._();

  factory TaskList([updates(TaskListBuilder b)]) = _$TaskList;
  static Serializer<TaskList> get serializer => _$taskListSerializer;
  static TaskList? fromJson(Map<String, dynamic> json) =>
      serializers.deserializeWith(serializer, json);

  Map<String, dynamic> toJson() => serializers.serializeWith(serializer, this) as Map<String, dynamic>;
}
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/loitran/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/loitran/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
```

```
built_collection:
    dependency: "direct main"
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.0"
  built_value:
    dependency: "direct main"
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.1.2"
  built_value_generator:
    dependency: "direct dev"
    description:
      name: built_value_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.1.1"
```
