### ISSUE TITLE
built_value has a dependency conflict with just_jwt

### ISSUE THREAD

**Issue by CasterKKK** [google/built_value.dart#433]
This is my `pubspec.yaml`.
```
dependencies:
  flutter_markdown: 0.1.5
  built_value: ^5.4.5
  shared_preferences: ^0.4.1
  just_jwt: ^1.3.1

  http: ^0.11.3+16

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^0.7.9
  built_value_generator: ^5.5.1
```

This is the conflict information.
```
Because reflectable >=0.5.1 <0.5.3 depends on analyzer 0.27.1 and pointycastle <=0.10.0+1 depends on reflectable ^0.5.1, pointycastle <=0.10.0+1 requires analyzer 0.27.1 or reflectable ^0.5.3.
And because every version of just_jwt depends on pointycastle ^0.10.0 and pointycastle >=0.10.0+2 <1.0.0-rc1 depends on reflectable ^1.0.1, every version of just_jwt requires analyzer 0.27.1 or reflectable ^0.5.3 or ^1.0.1.
And because reflectable >=1.0.4 <=2.0.0-dev.1.0 depends on analyzer ^0.30.0 and reflectable >=1.0.1 <1.0.4 depends on analyzer >=0.27.2 <0.30.0, every version of just_jwt requires analyzer 0.27.1 or >=0.27.2 <0.30.0 or ^0.30.0 or reflectable ^0.5.3.
And because reflectable >=0.5.3 <1.0.1 depends on analyzer ^0.27.2 and built_value_generator >=5.5.1 depends on analyzer ^0.32.1, built_value_generator >=5.5.1 is incompatible with just_jwt.
So, because tornado_blog_flutter depends on both just_jwt ^1.3.1 and built_value_generator ^5.5.1, version solving failed.
pub get failed (1)

```
