### ISSUE TITLE
Bump version of quiver

### ISSUE THREAD

**Issue by swissonid** [google/built_value.dart#457]
It look's that the dependent version (0.21.0 <= 0.30.0) of [quiver](https://pub.dartlang.org/packages/quiver) is pretty old. And now I got in trouble when I in a flutter project.

```bash
Because built_value_generator >=5.2.2 depends on quiver >=0.21.0 <0.30.0 and every version of flutter_test from sdk depends on quiver 2.0.0+1, built_value_generator >=5.2.2 is incompatible with flutter_test from sdk.
So, because flutterplayground depends on both flutter_test any from sdk and built_value_generator ^5.5.3, version solving failed.
```

Here my `pubspec.yaml` snipped.
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.9.2
  built_value_generator: ^5.5.3
```

Or do I something wrong?
