### ISSUE TITLE
`SerializersFor` fails after upgrading to `source_gen: 0.9.0` with "Broken @SerializersFor annotation"

### ISSUE THREAD

**Issue by filiph** [google/built_value.dart#492]
When upgrading from `source_gen: ^0.8.0` to `source_gen: ^0.9.0` (and no other change), a setup that has worked up until now suddenly fails with 

```
[SEVERE] built_value_generator|built_value on lib/edgehead_serializers.dart:
Error in BuiltValueGenerator for edgehead|lib/edgehead_serializers.dart.
Broken @SerializersFor annotation. Are all the types imported?
package:built_value_generator/src/serializer_source_library.dart 84:9
```

This is despite the fact that the static analyzer finds no issues with the `lib/edgehead_serializers.dart` file. Is there a new constraint for `@SerializersFor`? How do I debug this?

Here's the code that fails to build: https://github.com/filiph/egamebook/tree/source_gen_fail (clone this branch, then `cd edgehead`, then `pub get` and `pub run build_runner watch --verbose`).

**Comment by davidmorgan** [comment]
Thanks, I'll take a look as soon as I can--most likely early next week.

**Comment by davidmorgan** [comment]
By trial and error I discovered that it works if exactly `GuardpostAboveChurchTakeShieldRescueSituation` is commented out.

It looks like this file is also generated.

So I'm guessing it's something to do with generation order--and that your best bet is to ask Jake/Nate.

The `Broken @SerializersFor` message means that the analyzer returned null for the contents of the type--which it does if something in the list could not be analyzed. Normally this means a missing import. In this case it looks like analysis for built_value is running before the codegen for `GuardpostAboveChurchTakeShieldRescueSituation`.

**Comment by filiph** [comment]
Ahhh, thanks. For some reason analyzer didn't show any problems until after I visited that `GuardpostAboveChurchTakeShieldRescueSituation` file. Now I see exactly what the problem is.

This is going to be interesting, because the serializer codegen step depends on something that already needs to be codegen'd (because it's a Built class). But I'm pretty sure this is solvable.

**Comment by filiph** [comment]
For the record, the only thing that needed doing in the end was for my custom builder to have add the last two lines (`runs_before`) into its `build.yaml` file:

```
builders:
  # ...

  writers_builder:
    import: "package:egamebook_builder/writers_builder.dart"
    builder_factories: ["writersBuilder"]
    build_extensions: {".dart": [".compiled.dart"]}
    build_to: source
    auto_apply: none
    runs_before:
      - 'built_value_generator|built_value'
```

It was way simpler than I initially thought. Welp.
