### ISSUE TITLE
Reproduced Serialisation Bug:  method not found: 'name' on null  

### ISSUE THREAD

**Issue by rayk** [google/built_value.dart#664]
Hi @davidmorgan 

This would appear to be a simple problem, but it has me scratching my head. It is so simple it is likely to be my code. Anyhow I am reaching out because I can not see the problem. Any feedback would be helpful:

### Environment
- Dart 2.3.2
- Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- Mac OSX 10.14.5

### Short Description
When serialising a simple value, getting:

```NoSuchMethodError: method not found: 'name' on null``` 

#### - StackTrace

```
NoSuchMethodError: method not found: 'name' on null
  request_test.dart.browser_test.dart.js 1687:39    Object._runtimeTypeToString
  request_test.dart.browser_test.dart.js 1677:16    Object.runtimeTypeToString
  request_test.dart.browser_test.dart.js 11715:47   TypeImpl.get$_typeName
  request_test.dart.browser_test.dart.js 11722:81   TypeImpl.get$hashCode
  request_test.dart.browser_test.dart.js 3025:42    Object.get$hashCode$
  request_test.dart.browser_test.dart.js 11943:16   JsLinkedHashMap.internalComputeHashCode$1
  request_test.dart.browser_test.dart.js 11820:20   JsLinkedHashMap.internalSet$2
  request_test.dart.browser_test.dart.js 11811:15   JsLinkedHashMap.$indexSet
  request_test.dart.browser_test.dart.js 21022:27   BuiltJsonSerializersBuilder.add$1
  request_test.dart.browser_test.dart.js 29114:10   <fn>
  ===== asynchronous gap ===========================
  request_test.dart.browser_test.dart.js 12997:37   _SyncCompleter.completeError$2
  request_test.dart.browser_test.dart.js 12525:32   _AsyncAwaitCompleter.completeError$2
  request_test.dart.browser_test.dart.js 3234:57    Object._asyncRethrow
  request_test.dart.browser_test.dart.js 26010:20   <fn>
  request_test.dart.browser_test.dart.js 3259:15    _wrapJsFunctionForAsync_closure.$protected
  ===== asynchronous gap ===========================
  request_test.dart.browser_test.dart.js 14700:222  _CustomZone.registerBinaryCallback$3$1
  request_test.dart.browser_test.dart.js 3267:30    Object._wrapJsFunctionForAsync
  request_test.dart.browser_test.dart.js 26008:29   Declarer_test___closure.call$0
  request_test.dart.browser_test.dart.js 26337:51   <fn>
  request_test.dart.browser_test.dart.js 3259:15    _wrapJsFunctionForAsync_closure.$protected
  request_test.dart.browser_test.dart.js 12557:12   _wrapJsFunctionForAsync_closure.call$2
  ===== asynchronous gap ===========================
  request_test.dart.browser_test.dart.js 14700:222  _CustomZone.registerBinaryCallback$3$1
  request_test.dart.browser_test.dart.js 3267:30    Object._wrapJsFunctionForAsync
  request_test.dart.browser_test.dart.js 26326:29   Invoker_waitForOutstandingCallbacks_closure.call$0
  request_test.dart.browser_test.dart.js 3748:16    StaticClosure._rootRun
  request_test.dart.browser_test.dart.js 14652:158  _CustomZone.run$1$1
  request_test.dart.browser_test.dart.js 3923:89    Object._runZoned
  ===== asynchronous gap ===========================
  request_test.dart.browser_test.dart.js 14700:222  _CustomZone.registerBinaryCallback$3$1
  request_test.dart.browser_test.dart.js 3267:30    Object._wrapJsFunctionForAsync
  request_test.dart.browser_test.dart.js 25954:29   Declarer_test_closure.call$0
  request_test.dart.browser_test.dart.js 26482:107  <fn>
  request_test.dart.browser_test.dart.js 3259:15    _wrapJsFunctionForAsync_closure.$protected
  request_test.dart.browser_test.dart.js 12557:12   _wrapJsFunctionForAsync_closure.call$2
  ===== asynchronous gap ===========================
  request_test.dart.browser_test.dart.js 14700:222  _CustomZone.registerBinaryCallback$3$1
  request_test.dart.browser_test.dart.js 3267:30    Object._wrapJsFunctionForAsync
  request_test.dart.browser_test.dart.js 26473:29   Invoker__onRun____closure.call$0
  request_test.dart.browser_test.dart.js 12869:50   Future_Future_closure.call$0
  request_test.dart.browser_test.dart.js 25010:16   StackZoneSpecification._stack_zone_specification$_run$1$2
  request_test.dart.browser_test.dart.js 25050:26   StackZoneSpecification__registerCallback_closure.call$0
  ===== asynchronous gap ===========================
  request_test.dart.browser_test.dart.js 14682:174  _CustomZone.registerCallback$1$1
  request_test.dart.browser_test.dart.js 14612:71   _CustomZone.bindCallbackGuarded$1
  request_test.dart.browser_test.dart.js 3715:44    Object.Timer_Timer
  request_test.dart.browser_test.dart.js 3273:9     Object.Future_Future
  request_test.dart.browser_test.dart.js 26433:17   <fn>
  request_test.dart.browser_test.dart.js 3259:15    _wrapJsFunctionForAsync_closure.$protected
  ===== asynchronous gap ===========================
  request_test.dart.browser_test.dart.js 14700:222  _CustomZone.registerBinaryCallback$3$1
  request_test.dart.browser_test.dart.js 3267:30    Object._wrapJsFunctionForAsync
  request_test.dart.browser_test.dart.js 26422:29   Invoker__onRun___closure.call$0
  request_test.dart.browser_test.dart.js 3748:16    StaticClosure._rootRun
  request_test.dart.browser_test.dart.js 14652:158  _CustomZone.run$1$1
  request_test.dart.browser_test.dart.js 3923:89    Object._runZoned
```

#### - Test That Triggers Error

```dart
@TestOn('chrome')
import 'package:test/test.dart';
import 'package:logging/logging.dart';
import 'package:bad_build_value_serialize/bad_build_value_serialize.dart';

void main() {
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((lr) => print('${lr.toString()}'));
  Logger log = Logger('tstLog');

  group('Building Request:', () {
    test('Should return a request with min parametes.', () {
      var r = EdgeRequest((b) => b..id = 'id_for-serialize/request234');
      expect(r is EdgeRequest, isTrue);
    });

    test('Should serialize a min parameter request.', () {
      var req = EdgeRequest((b) => b..id = 'someId');
      var s = serializers.serialize(req);
    });
  });
}
```

#### - Value Declaration

```dart
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'request.g.dart';

abstract class EdgeRequest implements Built<EdgeRequest, EdgeRequestBuilder> {
  static Serializer<EdgeRequest> get serializer => _$edgeRequestSerializer;

  String get id;

  factory EdgeRequest([void Function(EdgeRequestBuilder) updates]) =
      _$EdgeRequest;

  EdgeRequest._();
}
```
#### - Generated Code

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'request.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializer<EdgeRequest> _$edgeRequestSerializer = new _$EdgeRequestSerializer();

class _$EdgeRequestSerializer implements StructuredSerializer<EdgeRequest> {
  @override
  final Iterable<Type> types = const [EdgeRequest, _$EdgeRequest];
  @override
  final String wireName = 'EdgeRequest';

  @override
  Iterable serialize(Serializers serializers, EdgeRequest object,
      {FullType specifiedType = FullType.unspecified}) {
    final result = <Object>[
      'id',
      serializers.serialize(object.id, specifiedType: const FullType(String)),
    ];

    return result;
  }

  @override
  EdgeRequest deserialize(Serializers serializers, Iterable serialized,
      {FullType specifiedType = FullType.unspecified}) {
    final result = new EdgeRequestBuilder();

    final iterator = serialized.iterator;
    while (iterator.moveNext()) {
      final key = iterator.current as String;
      iterator.moveNext();
      final dynamic value = iterator.current;
      switch (key) {
        case 'id':
          result.id = serializers.deserialize(value,
              specifiedType: const FullType(String)) as String;
          break;
      }
    }

    return result.build();
  }
}

class _$EdgeRequest extends EdgeRequest {
  @override
  final String id;

  factory _$EdgeRequest([void Function(EdgeRequestBuilder) updates]) =>
      (new EdgeRequestBuilder()..update(updates)).build();

  _$EdgeRequest._({this.id}) : super._() {
    if (id == null) {
      throw new BuiltValueNullFieldError('EdgeRequest', 'id');
    }
  }

  @override
  EdgeRequest rebuild(void Function(EdgeRequestBuilder) updates) =>
      (toBuilder()..update(updates)).build();

  @override
  EdgeRequestBuilder toBuilder() => new EdgeRequestBuilder()..replace(this);

  @override
  bool operator ==(Object other) {
    if (identical(other, this)) return true;
    return other is EdgeRequest && id == other.id;
  }

  @override
  int get hashCode {
    return $jf($jc(0, id.hashCode));
  }

  @override
  String toString() {
    return (newBuiltValueToStringHelper('EdgeRequest')..add('id', id))
        .toString();
  }
}

class EdgeRequestBuilder implements Builder<EdgeRequest, EdgeRequestBuilder> {
  _$EdgeRequest _$v;

  String _id;
  String get id => _$this._id;
  set id(String id) => _$this._id = id;

  EdgeRequestBuilder();

  EdgeRequestBuilder get _$this {
    if (_$v != null) {
      _id = _$v.id;
      _$v = null;
    }
    return this;
  }

  @override
  void replace(EdgeRequest other) {
    if (other == null) {
      throw new ArgumentError.notNull('other');
    }
    _$v = other as _$EdgeRequest;
  }

  @override
  void update(void Function(EdgeRequestBuilder) updates) {
    if (updates != null) updates(this);
  }

  @override
  _$EdgeRequest build() {
    final _$result = _$v ?? new _$EdgeRequest._(id: id);
    replace(_$result);
    return _$result;
  }
}

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new
```
#### - Build Config

```yaml
targets:
  $default:
    sources:
      - lib/**
      - test/**
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - lib/**
          - test/**
        dev_options:
          compiler: dart2js
          dart2js_args:
            - --show-package-warnings
            - --enable-diagnostic-colors
            - --verbose
            - --enable-asserts
            - -DDEBUGGER_ON=true
            - -O1
        release_options:
          compiler: dart2js
          dart2js_args:
            - --verbose
            - -DDEBUGGER_ON=false
            - -DLOCAL_DEPLOY=false
            - -DRELEASE_BUILD=true
            - -O4
```

#### - PubSpec

```yaml
name: bad_build_value_serialize
description: A starting point for Dart libraries or applications.
version: 1.0.3
repository: https://github.com/criticide/critiapp
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: ^4.2.2
  built_value: ^6.6.0
  collection: ^1.14.11
  js: ^0.6.1+1
  meta: ^1.1.7
  pub_semver: ^1.4.2
  nanoid: ^0.1.0
  rxdart: ^0.22.0
  stream_channel: ^2.0.0
  tuple: ^1.0.2
  uuid: ^2.0.1

dev_dependencies:
  build_config: ^0.4.0
  build_runner: ^1.5.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.1
  built_value_generator: ^6.6.0
  mockito: ^4.0.0
  pedantic: ^1.7.0
  test: ^1.6.4
```

I have also attached a zip of the Intellij project in which I have managed to recreate this problem in a standalone fashion.

Thanks in advance.
[bad_build_value_serialize.zip](https://github.com/google/built_value.dart/files/3288676/bad_build_value_serialize.zip)
