### ISSUE TITLE
Changes necessary when linter rules are enabled

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#70]
Not everyone wants to enable all these rules but it would be great if the generated code would conform to most

My `.analysis_options`

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

#  language:
#    enableGenericMethods: true

  exclude:
#    - 'build/**'
#    - '**.g.dart'
    - 'bazel-*'

linter:
  rules:
# Error Rules
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps

# Style Rules
    - always_declare_return_types
#    - always_specify_types
    - annotate_overrides
#    - avoid_as
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - parameter_assignments
    - prefer_final_fields
    - prefer_final_locals
#    - public_member_api_docs
    - slash_for_doc_comments
#    - sort_constructor_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters

# Pub Rules
    - package_names
```

My input source files

```dart
library model2;

import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'component_target_type.dart';
import 'package:meta/meta.dart';

part 'component.g.dart';

abstract class Component implements Built<Component, ComponentBuilder> {
  String get name;
  String get importPath;
  String get className;
  String get tagName;
  ComponentTargetType get targetType;
  String get targetName;

  static Serializer<Component> get serializer => _$componentSerializer;

  factory Component([void updates(ComponentBuilder b)]) = _$Component;
  Component._();
}
```
```dart
library model2;

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'component_target_type.g.dart';

class ComponentTargetType extends EnumClass {
  static const ComponentTargetType custom = _$custom;
  static const ComponentTargetType fieldType = _$fieldType;
  static const ComponentTargetType fieldTypeList = _$fieldTypeList;
  static const ComponentTargetType backboneElement = _$backboneElement;
  static const ComponentTargetType extension = _$extentions;
  static const ComponentTargetType resource = _$resource;

  static final Serializer<ComponentTargetType> serializer =
      _$componentTargetTypeSerializer;

  const ComponentTargetType._(String name) : super(name);

  static BuiltSet<ComponentTargetType> get values => _$values;
  static ComponentTargetType valueOf(String name) => _$valueOf(name);
}
```

The changes I made to get rid of the linter hints/warnings

![image](https://cloud.githubusercontent.com/assets/405837/20642811/a083abf2-b419-11e6-9a01-6370834bf681.png)
![image](https://cloud.githubusercontent.com/assets/405837/20642815/b4a46a36-b419-11e6-9106-602dda2b9868.png)

![image](https://cloud.githubusercontent.com/assets/405837/20642820/d668df9e-b419-11e6-88ba-3688c0e50193.png)
