### ISSUE TITLE
Version solving failed on build_value_generator

### ISSUE THREAD

**Issue by amlwin** [google/built_value.dart#706]
When I start use [Inject.dart](https://github.com/google/inject.dart) on flutter project .Issue arise on `built_value_generator` like this. 
```
Because no versions of built_value_generator match >6.7.1 <7.0.0 and built_value_generator 6.7.1 depends on analyzer_plugin >=0.1.0 <0.3.0, built_value_generator ^6.7.1 requires analyzer_plugin >=0.1.0 <0.3.0.
And because no versions of analyzer_plugin match >0.1.0 <0.3.0, built_value_generator ^6.7.1 requires analyzer_plugin 0.1.0.
And because analyzer_plugin 0.1.0 depends on analyzer >=0.35.3 <0.38.0 and every version of inject_generator from git depends on analyzer ^0.34.0, built_value_generator ^6.7.1 is incompatible with inject_generator from git.
So, because xxx depends on both inject_generator from git and built_value_generator ^6.7.1, version solving failed.



pub get failed (1)
```
Is any suggestion to resolve this?. Here my `pubspec.yaml`. 
```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  built_value: ^6.7.1
  built_collection: ^4.2.2
  redux_logging: ^0.3.0
  http: ^0.12.0+2
  inject:
    git:
      url : https://github.com/google/inject.dart.git
      path: package/inject

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^6.7.1
  build_runner: ^1.6.9
  mockito: ^4.1.1
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator

flutter:
  uses-material-design: true
```
Output of `flutter doctor`..
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.1 18B75, locale
    en-MM)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.5)
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
[✓] VS Code (version 1.38.0)
[✓] Connected device (1 available)

• No issues found!
```
Thank you all!
