### ISSUE TITLE
Question: Generating for multi-package projects

### ISSUE THREAD

**Issue by Hacker-CB** [google/built_value.dart#714]
Hello!
Could you help with next situation:

Project structure:

```
app/pubspec.yaml
packages/app_part/pubspec.yaml
Both projects are using built_value immutable models.
```

app/pubspec.yaml:

```
name: app
dependencies:
  built_value: ^6.7.1
  app_part:
    path: ../packages/app_part
dev_dependencies:
  build_runner: ^1.6.7
  built_value_generator: ^6.7.1
```

packages/app_part/pubspec.yaml:

```
name: app_part
dependencies:
  built_value: ^6.7.1
dev_dependencies:
  build_runner: ^1.6.7
  built_value_generator: ^6.7.1
```
I'm executing `pub run build_runner watch` inside app folder of the project during development.

`built_value_generator` generates `.g.dart` only for sources which are located in `app`, not in `packages/app_part`

**So, how to run `build_runner watch` to generate code for all `app` dependencies)?**
Actually I need at least local dependencies, specified with `path`
