### ISSUE TITLE
Version Solving Failed

### ISSUE THREAD

**Issue by kirkcharlesniv** [google/built_value.dart#741]
When running `flutter packages get`, it throws out this error:
```
Running "flutter pub get" in built_value_test...                
Because no versions of build_runner match >1.7.2 <2.0.0 and build_runner 1.7.2 depends on build_daemon ^2.1.0, build_runner ^1.7.2 requires build_daemon ^2.1.0.


Because build_daemon 2.1.0 depends on built_value ^6.3.0 and no versions of build_daemon match >2.1.0 <3.0.0, build_daemon ^2.1.0 requires built_value ^6.3.0.
Thus, build_runner ^1.7.2 requires built_value ^6.3.0.

So, because built_value_test depends on both built_value ^7.0.0 and build_runner ^1.7.2, version solving failed.
pub get failed (1; So, because built_value_test depends on both built_value ^7.0.0 and build_runner ^1.7.2, version solving failed.)
exit code 1
```

Take note that my Flutter gets update from the **master** branch.

**pubspec.yaml**
```
name: built_value_test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
flutter:
  uses-material-design: true
```

**flutter doctor -v**
```
[√] Flutter (Channel master, v1.10.15-pre.384, on Microsoft Windows [Version 10.0.18362.418], locale en-PH)
    • Flutter version 1.10.15-pre.384 at D:\dev\flutter
    • Framework revision ee032f67c7 (21 hours ago), 2019-11-02 09:46:25 -0700
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Kirk Charles Niverba\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**flutter analyze**
```
Analyzing built_value_test...
No issues found! (ran in 1.7s)
```
