### ISSUE TITLE
serializers.g.dart can cannot be generated

### ISSUE THREAD

**Issue by huangyanxiong01** [google/built_value.dart#747]
`user.dart`

```dart
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'user.g.dart';

abstract class User implements Built<User, UserBuilder> {
  static Serializer<User> get serializer => _$userSerializer;

  String get name;

  String get email;

  int get id;

  @nullable
  String get nodeId;

  @nullable
  String get avatar_url;

  @nullable
  String get url;

  @BuiltValueField(wireName: 'starred_url')
  String get starredUrl;

  String get password;

  User._();

  factory User([void Function(UserBuilder) updates]) = _$User;

}

```

`serializers.dart`

```dart
library serializers;

import 'package:GTA/pages/login/models/user.dart';


part 'serializers.g.dart';



@SerializersFor([  
  User,
])

final Serializers serializers = _$serializers;
````

`pubspec.yaml`
```yaml
name: GTA
description: Github Trending App
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  http: ^0.12.0+2
  path_provider: ^1.3.1
  github_trend: ^1.1.9
  flutter_launcher_icons: ^0.7.0
  webview_flutter: ^0.3.9+1
  mockito: ^4.1.1
  github: ^5.4.0
  flutter_redux_dev_tools: ^0.3.0
  flutter_built_redux: ^0.6.0
  built_redux: ^7.5.6
  built_value: ^6.8.2
  built_collection: ^4.2.2

dev_dependencies:
  build_runner: ^1.7.1
  built_value_generator: ^6.8.2
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/github-6-128.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```
the `build_runner` have not show anything  error message

```shell
flutter pub pub run build_runner  watch  --delete-conflicting-outputs
```
