### ISSUE TITLE
Watcher crashed for emacs temp file

### ISSUE THREAD

**Issue by bradyt** [google/built_value.dart#834]
Seems to be similar to this issue: https://github.com/dart-lang/build/issues/1134.

If I use `pub run build_runner watch`, and edit a file with Emacs, 

```
[SEVERE] built_value_generator:built_value on lib/src/.#types.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] Unhandled build failure!
FileSystemException: Cannot create file, path = '.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/cone_lib/0/lib/src/.' (OS Error: Is a directory, errno = 21)
[SEVERE] Failed after 7ms
```

Environment information:
```
$ dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "macos_x64"
```

```yaml
# pubspec.lock
...
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.4"
...
  built_value:
    dependency: "direct main"
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.0.9"
  built_value_generator:
    dependency: "direct dev"
    description:
      name: built_value_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.0.9"
...
```
