### ISSUE TITLE
Bump `analyzer` version for compatibility with `build_runner` >= 1.10.3

### ISSUE THREAD

**Issue by MichaelM97** [google/built_value.dart#923]
`build_runner` v1.10.3+ is required to use Dart SDK >=2.10.0

`built_value_generator` is causing a compatibility issue with this due to the following:

```
Because no versions of built_value_generator match >7.1.0 <8.0.0 and built_value_generator 7.1.0 
depends on analyzer ^0.39.3, built_value_generator ^7.1.0 requires analyzer ^0.39.3.

And because build_runner >=1.10.3 depends on build_resolvers ^1.4.0 which depends on analyzer 
^0.40.1, built_value_generator ^7.1.0 is incompatible with build_runner >=1.10.3.
```

In the latest stable release of Flutter (`1.22.0`) the Dart SDK has been bumped to `2.10.0`, so this is blocking me updating to the latest Flutter release

**Comment by bakua** [comment]
```
dev_dependencies:
  build_runner: ^1.10.3
  built_value_generator: ^7.1.0

dependency_overrides:
  analyzer: 0.40.4
```

Works for me
